config/routes.rb
HaveTodo::Application.routes.draw do
  root "welcome#index"
  
  get "blank" => "welcome#blank"

  get "stayawake" => "stayawake#index"

  devise_for :users, :controllers => { :registrations => :registrations, :sessions => :sessions }

  devise_scope :user do
    get 'registrations' => 'registrations#new'
    post 'registrations' => 'registrations#create'

    get '/users/sign_up' => 'registration#new'
    post '/users' => 'registration#create'
    get '/users/edit' => 'registration#edit'
    get '/users/cancel' => 'registration#cancel'

    get '/users/sign_in' => 'sessions#new'
    post '/users/sign_in' => 'sessions#create'
    delete '/users/sign_out' => 'sessions#destroy'
    
    get '/users' => 'users#show'
    
  end

  resources :tasks, path: '/users/tasks' do
    resources :task_comments
    
    post '/toggleComplete' => 'tasks#toggleComplete'
    post '/addFriend/:user_id' => 'tasks#addFriend', as: 'addFriend'
    post '/removeFriend/:user_id' => 'tasks#removeFriend', as: 'removeFriend'
  end
  
  resources :tasklists, path: '/users/tasklists' do
    resources :tasks do
    end

    post '/addFriend/:user_id' => 'tasklists#addFriend', as: 'addFriend'
    post '/removeFriend/:user_id' => 'tasklists#removeFriend', as: 'removeFriend'

  end
  
  resources :friendships, path: '/users/friendships' do
    post '/acceptFriend' => 'friendships#acceptFriend'
    post '/rejectFriend' => 'friendships#rejectFriend'
  end

  namespace :api do
    devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
    end
  end
  

end

app/models/tasklist.rb
class Tasklist < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :tasks
  
  attr_accessible :name, :color

  validates :name, presence: true
  validates :color, presence: true

=begin
  def to_param
    "#{id}-#{name}"
  end
=end

end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController

  layout 'tasklist'

  skip_before_filter :verify_authenticity_token,
                     :if => Proc.new { |c| c.request.format == 'application/json' }
                       
  before_filter :authenticate_user!
  before_filter :validate_user
  
  before_action :get_user
  before_action :get_tasklists
  before_action :share_tasklist
#  before_action :set_task, only: [:show, :edit, :update, :destroy]

  before_action :set_tasklist, only: [:show, :edit, :update, :destroy]
  

  # GET /tasklists
  # GET /tasklists.json
  def index
#    @tasklists = Tasklist.all
#    @tasklists = @user.tasklists
  end

  # GET /tasklists/1
  # GET /tasklists/1.json
  def show
#    @new_task = Task.new
    @new_task = @user.tasks.build
#    @task = @user.tasks.build(task_params)

    share_tasklist

#    @tasklists = @user.tasklists

    @tasks = @tasklist.tasks
    
    @overdue_tasks = @tasks.overdue_tasks.order(:due_date).order(:due_time).order(:name)
    @today_tasks = @tasks.today_tasks.order(:due_date).order(:due_time).order(:name)
    @tomorrow_tasks = @tasks.tomorrow_tasks.order(:due_date).order(:due_time).order(:name)
    @this_week_tasks = @tasks.this_week_tasks.order(:due_date).order(:due_time).order(:name)
    @future_tasks = @tasks.future_tasks.order(:due_date).order(:due_time).order(:name)
    
    @no_duedate_tasks = @tasks.no_duedate_tasks.order(:name)
    @completed_tasks = @tasks.completed_tasks.order(:completed_date).reverse_order
    
  end

  # GET /tasklists/new
  def new
    @tasklist = Tasklist.new
  end

  # GET /tasklists/1/edit
  def edit
  end

  # POST /tasklists
  # POST /tasklists.json
  def create
    @tasklist = Tasklist.new(tasklist_params)

    respond_to do |format|
      if @tasklist.save
        @user.tasklists << @tasklist
        
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tasklist }
      else
        format.html { render action: 'new' }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasklists/1
  # PATCH/PUT /tasklists/1.json
  def update
    respond_to do |format|
      if @tasklist.update(tasklist_params)
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasklists/1
  # DELETE /tasklists/1.json
  def destroy
    @tasklist.destroy
    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.json { head :no_content }
    end
  end

  def validate_user
    redirect_to new_user_session_path unless current_user
  end

  def addFriend
    @friend = User.find(params[:user_id])
    @tasklist = @user.tasklists.find(params[:tasklist_id])
    @tasklist.users << @friend
    
    @tasklist.tasks.each do |t|
      @friend.tasks << t
    end

    respond_to do |format|
      format.html { 
        flash[:success] = "Successfully shared tasklist with #{@friend.name}" 
        redirect_to :back
      }
      format.json 
    end    
  end

  def removeFriend
    @friend = User.find(params[:user_id])
    @tasklist = @user.tasklists.find(params[:tasklist_id])

#    share_tasklist

    respond_to do |format|
      if @friend == @user
        format.html { 
          flash[:danger] = "Cannot remove yourself." 
          redirect_to :back
        }
        format.json 
      elsif !@friends.include? @friend.id
        format.html { 
          flash[:danger] = "#{@friend.name} is not your friend, cannot remove from task." 
          redirect_to :back
        }
        format.json 
      else
        @tasklist.users.delete(@friend)
        
        @tasklist.tasks do |t|
          @friend.tasks.delete(t)
        end
        
        format.html { 
          flash[:success] = "#{@friend.name} successfully removed from task." 
          redirect_to :back
        }
        format.json 
      end
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_user
      @user = User.find(current_user.id)
    end

    def get_tasklists
      @tasklists = @user.tasklists.order(:name)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_tasklist
      get_user

      @tasklist = Tasklist.find(params[:id])
    end

    def share_tasklist
      @friends = @user.friendships.accepted.pluck(:friend_id)
      @friends = @friends + @user.inverse_friendships.accepted.pluck(:user_id)
    
#      @tasklist_shared = @tasklist.users.pluck(:id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tasklist_params
      params.require(:tasklist).permit(:name, :color)
    end
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/views/tasklists/_form.html.erb
<%= form_for(@tasklist) do |f| %>
  <% if @tasklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tasklist.errors.count, "error") %> prohibited this tasklist from being saved:</h2>

      <ul>
      <% @tasklist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasklists/_share_tasklist.html.erb
<h2>Share with Friends</h2>

<% if @friends.nil? or @friends.empty? %>
You have no Friends.  Please add some friends to your <%= link_to "Friend List", friendships_path %>.
<% elsif (@friends - tasklist.users.pluck(:id)).empty? %>
Task assigned to all your friends
<% else %>
<ul>
	<% for u in (User.order(:name).find(@friends - tasklist.users.pluck(:id))) %>
	  <li><%= link_to u.name, tasklist_addFriend_path(tasklist, u), method: :post %></li>
	<% end %>
</ul>
<% end %>


<h2>Sharing To (click the name to remove)</h2>

<ul>
	<% for u in (User.order(:name).find(tasklist.users.pluck(:id))) %>
	  <li>
	  	<%= link_to u.name, tasklist_removeFriend_path(tasklist, u), method: :post %>
	  </li>
	<% end %>
</ul>

app/views/tasklists/_tasklist_functions.html.erb
&nbsp;
<div class="dropdown-sidebar-functions">
	<span id="tasklist functions" class="icon-pencil dropdown-toggle" data-toggle="dropdown"></span>
    <ul class="dropdown-menu" role="menu">
    <li class="left">
      <a href="#" data-toggle="modal" onclick="ShareTasklistModal(<%= tasklist.id.to_s %>)">Share</a>
    </li>
    <hr>
    <li class="left">
      <a href="#" data-toggle="modal" onclick="EditTasklistModal(<%= tasklist.id.to_s %>)">Edit</a> 
    </li>
    <hr>
    <li class="left">
      <%= link_to tasklist, method: :delete, data: { confirm: 'Are you sure?' } do %>
        Delete
      <% end %>
    </li>
	</ul>
</div>


<!-- Modal -->
<div class="modal fade" id=<%= "EditTasklistModal_"+tasklist.id.to_s %> tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit TaskList</h4>
      </div>
      <div class="modal-body">
      	<%= form_for tasklist do |f| %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, :autofocus => true %>
        </div>
        <div class="field">
          <%= f.label :color %>
          <%= color_field(:tasklist, :color, {value: tasklist.color}) %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Update', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id=<%= "ShareTasklistModal_"+tasklist.id.to_s %> tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Share TaskList <%= tasklist.name %></h4>
      </div>
      <div class="modal-body">
     	<%= render 'tasklists/share_tasklist', :tasklist => tasklist %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Done</button>
      </div>
    </div>
  </div>
</div>

app/views/tasklists/_tasklist_script.html.erb
<script>

/////////////////////////////////////////////////////////////////////////

function EditTasklistModal(id) {
	var temp = '#EditTasklistModal_'+id;
	$(temp).modal('show');
}


function ShareTasklistModal(id) {
	var temp = '#ShareTasklistModal_'+id;
	$(temp).modal('show');
}

/////////////////////////////////////////////////////////////////////////

$(".modal").on('shown.bs.modal', function () {
    $(this).find("[autofocus]:first").focus();
})

/////////////////////////////////////////////////////////////////////////

function getRandomColor() {
    var letters = '0123456789ABCDEF'.split('');
    var color = '#';
    for (var i = 0; i < 6; i++ ) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}

/////////////////////////////////////////////////////////////////////////

</script>

app/views/tasklists/edit.html.erb
<h1>Editing tasklist</h1>

<%= render 'form' %>

<%= link_to 'Show', @tasklist %> |
<%= link_to 'Back', tasklists_path %>

app/views/tasklists/index.html.erb
<h1>Listing tasklists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasklists.each do |tasklist| %>
      <tr>
        <td><%= tasklist.name %></td>
        <td><%= link_to 'Show', tasklist %></td>
        <td><%= link_to 'Edit', edit_tasklist_path(tasklist) %></td>
        <td><%= link_to 'Destroy', tasklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tasklist', new_tasklist_path %>

app/views/tasklists/new.html.erb
<h1>New tasklist</h1>

<%= render 'form' %>

<%= link_to 'Back', tasklists_path %>

app/views/tasklists/show.html.erb
<h2>
  <div class="circle" style="background-color: <%= @tasklist.color %>;" ></div>
  <%= @tasklist.name %>
  <%= render 'tasklists/tasklist_functions', :tasklist => @tasklist %>
</h2>

<%= render 'tasks/simple_add', :style => "display:inline" %>

<div id="list_tables">
<% if !@overdue_tasks.empty? %>
<%= render partial: 'tasks/overdue_task_table', locals: { task_header: "Overdue", task_table: @overdue_tasks } %>
<% end %>

<% if !@today_tasks.empty? %>
<%= render partial: 'tasks/incomplete_task_table', locals: { task_header: "Today", task_table: @today_tasks } %>
<% end %>

<% if !@tomorrow_tasks.empty? %>
<%= render partial: 'tasks/incomplete_task_table', locals: { task_header: "Tomorrow", task_table: @tomorrow_tasks } %>
<% end %>

<% if !@this_week_tasks.empty? %>
<%= render partial: 'tasks/incomplete_task_table', locals: { task_header: "This Week", task_table: @this_week_tasks } %>
<% end %>

<% if !@future_tasks.empty? %>
<%= render partial: 'tasks/incomplete_task_table', locals: { task_header: "Future", task_table: @future_tasks } %>
<% end %>

<% if !@no_duedate_tasks.empty? %>
<%= render partial: 'tasks/incomplete_task_table', locals: { task_header: "No DueDate", task_table: @no_duedate_tasks } %>
<% end %>

<% if !@completed_tasks.empty? %>
<%= render partial: 'tasks/completed_task_table', locals: { task_header: "Completed", task_table: @completed_tasks } %>
<% end %>
</div>