config/routes.rb
HaveTodo::Application.routes.draw do
  root "welcome#index"
  
  get "blank" => "welcome#blank"

  get "stayawake" => "stayawake#index"

  devise_for :users, :controllers => { :registrations => :registrations, :sessions => :sessions }

  devise_scope :user do
    get 'registrations' => 'registrations#new'
    post 'registrations' => 'registrations#create'

    get '/users/sign_up' => 'registration#new'
    post '/users' => 'registration#create'
    get '/users/edit' => 'registration#edit'
    get '/users/cancel' => 'registration#cancel'

    get '/users/sign_in' => 'sessions#new'
    post '/users/sign_in' => 'sessions#create'
    delete '/users/sign_out' => 'sessions#destroy'
    
    get '/users' => 'users#show'
    
  end

  resources :tasks, path: '/users/tasks' do
    resources :task_comments
    
    post '/toggleComplete' => 'tasks#toggleComplete'
    post '/addFriend/:user_id' => 'tasks#addFriend', as: 'addFriend'
    post '/removeFriend/:user_id' => 'tasks#removeFriend', as: 'removeFriend'
  end
  
  resources :tasklists, path: '/users/tasklists' do
    resources :tasks do
    end

    post '/addFriend/:user_id' => 'tasklists#addFriend', as: 'addFriend'
    post '/removeFriend/:user_id' => 'tasklists#removeFriend', as: 'removeFriend'

  end
  
  resources :friendships, path: '/users/friendships' do
    post '/acceptFriend' => 'friendships#acceptFriend'
    post '/rejectFriend' => 'friendships#rejectFriend'
  end

  namespace :api do
    devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
    end
  end
  

end

app/models/task_comment.rb
class TaskComment < ActiveRecord::Base

  attr_accessible :comment
  
  belongs_to :task

end

app/controllers/task_comments_controller.rb
class TaskCommentsController < ApplicationController

  skip_before_filter :verify_authenticity_token,
                     :if => Proc.new { |c| c.request.format == 'application/json' }
                       
  before_filter :authenticate_user!
  before_filter :validate_user

  before_action :get_user
  before_action :get_task
  before_action :get_task_comments
  

  before_action :set_task_comment, only: [:show, :edit, :update, :destroy]

  # GET /task_comments
  # GET /task_comments.json
  def index
#    @task_comments = TaskComment.all
  end

  # GET /task_comments/1
  # GET /task_comments/1.json
  def show
  end

  # GET /task_comments/new
  def new
    @task_comment = TaskComment.new
  end

  # GET /task_comments/1/edit
  def edit
  end

  # POST /task_comments
  # POST /task_comments.json
  def create
    @task_comment = TaskComment.new(task_comment_params)

    respond_to do |format|
      if @task_comment.save
        format.html { 
          flash[:success] = "Task Comment was successfully added." 
          redirect_to @task
        }
        format.json { render action: 'show', status: :created, location: @task_comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @task_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_comments/1
  # PATCH/PUT /task_comments/1.json
  def update
    respond_to do |format|
      if @task_comment.update(task_comment_params)
        format.html { 
          flash[:success] = "Task comment was successfully updated." 
          redirect_to @task
        }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_comments/1
  # DELETE /task_comments/1.json
  def destroy
    @task_comment.destroy
    respond_to do |format|
      format.html { 
          flash[:success] = "Task comment was successfully deleted." 
          redirect_to @task
      }
      format.json { head :no_content }
    end
  end

  def validate_user
    redirect_to new_user_session_path unless current_user
  end


  private
    def get_user
      @user = User.find(current_user.id)
    end
    
    def get_task
      @task = @user.tasks.find(params[:task_id])
    end
    
    def get_task_comments
      @task_comments = @task.task_comments
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task_comment
      @task_comment = @task.task_comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_comment_params
      params.require(:task_comment).permit(:task_id, :user_id, :user_name, :comment)
    end
end

app/helpers/task_comments_helper.rb
module TaskCommentsHelper
end

app/views/task_comments/_form.html.erb
<%= form_for(@task_comment) do |f| %>
  <% if @task_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_comment.errors.count, "error") %> prohibited this task_comment from being saved:</h2>

      <ul>
      <% @task_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_comments/edit.html.erb
<h1>Editing task_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_comment %> |
<%= link_to 'Back', task_comments_path %>

app/views/task_comments/index.html.erb
<h1>Listing task_comments</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>User</th>
      <th>User name</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @task_comments.each do |task_comment| %>
      <tr>
        <td><%= task_comment.task_id %></td>
        <td><%= task_comment.user_id %></td>
        <td><%= task_comment.user_name %></td>
        <td><%= task_comment.comment %></td>
        <td><%= link_to 'Show', task_comment %></td>
        <td><%= link_to 'Edit', edit_task_comment_path(task_comment) %></td>
        <td><%= link_to 'Destroy', task_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task comment', new_task_comment_path %>

app/views/task_comments/new.html.erb
<h1>New task_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', task_comments_path %>

app/views/task_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @task_comment.task_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @task_comment.user_id %>
</p>

<p>
  <strong>User name:</strong>
  <%= @task_comment.user_name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @task_comment.comment %>
</p>

<%= link_to 'Edit', edit_task_comment_path(@task_comment) %> |
<%= link_to 'Back', task_comments_path %>