config/routes.rb
HaveTodo::Application.routes.draw do
  root "welcome#index"
  
  get "blank" => "welcome#blank"

  get "stayawake" => "stayawake#index"

  devise_for :users, :controllers => { :registrations => :registrations, :sessions => :sessions }

  devise_scope :user do
    get 'registrations' => 'registrations#new'
    post 'registrations' => 'registrations#create'

    get '/users/sign_up' => 'registration#new'
    post '/users' => 'registration#create'
    get '/users/edit' => 'registration#edit'
    get '/users/cancel' => 'registration#cancel'

    get '/users/sign_in' => 'sessions#new'
    post '/users/sign_in' => 'sessions#create'
    delete '/users/sign_out' => 'sessions#destroy'
    
    get '/users' => 'users#show'
    
  end

  resources :tasks, path: '/users/tasks' do
    resources :task_comments
    
    post '/toggleComplete' => 'tasks#toggleComplete'
    post '/addFriend/:user_id' => 'tasks#addFriend', as: 'addFriend'
    post '/removeFriend/:user_id' => 'tasks#removeFriend', as: 'removeFriend'
  end
  
  resources :tasklists, path: '/users/tasklists' do
    resources :tasks do
    end

    post '/addFriend/:user_id' => 'tasklists#addFriend', as: 'addFriend'
    post '/removeFriend/:user_id' => 'tasklists#removeFriend', as: 'removeFriend'

  end
  
  resources :friendships, path: '/users/friendships' do
    post '/acceptFriend' => 'friendships#acceptFriend'
    post '/rejectFriend' => 'friendships#rejectFriend'
  end

  namespace :api do
    devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
    end
  end
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    HaveTodo by Gordon Kwok
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "HaveTodo app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if user_signed_in? %>          
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            	<%= current_user.name %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
 	            <li><%= link_to "Profile", edit_user_registration_path %></li>
 	            <li><%= link_to "Task List", tasks_path %></li>
 	            <li><%= link_to "Friend List", friendships_path %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>	
            </li>
            <% else %>
	          <li><%= link_to "Home", root_path %></li>
    	      <li><%= link_to "Help", '#' %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HaveTodo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/layouts/tasklist.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HaveTodo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>
<body>
  <%= render 'tasks/task_script' %>
  <%= render 'tasklists/tasklist_script' %>

  <%= render 'layouts/header' %>
  <div class="well" id="sidebar"> 
    <ul class="sidebar" style="list-style-type: none;">
      <li>
      	<%= link_to tasks_path do %>
      	  All Tasks <span class="badge"><%= current_user.tasks.incomplete_tasks.count %></span>
      	<% end %>
      </li>
    </ul>
    
    <hr>

    <ul class="sidebar" style="list-style-type: none;">
      <li>Task Lists</li>
	<% if !@tasklists.empty? %>
      	<% @tasklists.each do |tl| %>
      	  <li class="sidebar">
        	<div class="circle super" style="background-color: <%= tl.color %>;" ></div>
      	  	<div class="trim_tasklist_name" title="<%= tl.name %>">
      	  	  <%= link_to tl do %>
         	    <%= tl.name %>
              <% end %>
      	  	</div>
            <span class="badge right"><%= tl.tasks.incomplete_tasks.count %></span>
            <%= render 'tasklists/tasklist_functions', :tasklist => tl %>
      	  </li>
      	<% end %>
    <% end %>
      <li><a id="CreateTasklist" href="#" data-toggle="modal" data-target="#CreateTasklistModal">Create Task List</a></li>
    </ul>
  </div>

  <div id="taskarea">
	<div class="row">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </div>

<!-- Modal -->
<div class="modal fade" id="CreateTasklistModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create TaskList</h4>
      </div>
      <div class="modal-body">
      	<%= form_for (Tasklist.new) do |f| %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, :autofocus => true %>
        </div>
        <div class="field">
          <%= f.label :color %>
          <%= color_field(:tasklist, :color, {value: "#%06x" % (rand * 0xffffff)}) %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Create', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
$('#CreateTasklistModal').on('shown.bs.modal', function () {
    $(this).find("[autofocus]:first").focus();
    $(this).find("#tasklist_color").val(getRandomColor());
})

</script>

</body>
</html>